[tasks.default]
clear = true
script = '''
#!/usr/bin/env bash
set -euo pipefail
VERSION=$CARGO_MAKE_PROJECT_VERSION
PACKAGE=$CARGO_MAKE_PROJECT_NAME
export RELEASE=1
export ARCH=x86_64-unknown-linux-gnu 
BUILD_OUT=target-cross/$ARCH/release/
mkdir -p $BUILD_OUT
cp ltapiserv-rs.service $BUILD_OUT
OUT=target-cross/packages
mkdir -p $OUT

cargo about generate about.hbs > $BUILD_OUT/licenses.html
cross build -r --target $ARCH --target-dir target-cross

DEST=$OUT/$PACKAGE-$VERSION-$RELEASE-$ARCH.tar.gz
tar czf $DEST -C $BUILD_OUT ltapiserv-rs ltapi-client ltapiserv-rs.service licenses.html
tar tvf $DEST

for PACKAGER in deb archlinux; do
    nfpm pkg --packager $PACKAGER -t $OUT
done
ls -lh $OUT
git cliff -l
'''
